package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.triggers.FinishBuildTrigger
import jetbrains.buildServer.configs.kotlin.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildEditor'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildEditor")) {
    triggers {
        val trigger1 = find<FinishBuildTrigger> {
            finishBuildTrigger {
                buildType = "DevPub_UnrealEngine5_FetchSource"
                successfulOnly = true
            }
        }
        trigger1.apply {
            branchFilter = "+:*"

        }
    }
}
