package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.PowerShellStep
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildEditor'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildEditor")) {
    expectSteps {
        powerShell {
            name = "Build UE5 Installed Engine"
            id = "jetbrains_powershell"
            scriptMode = script {
                content = """
                    ${'$'}ErrorActionPreference = 'Stop'
                    
                    # UTF-8 codepage (cmd의 chcp 65001 대응)
                    chcp 65001 | Out-Null
                    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
                    
                    # MaxParallelActions를 머신 BuildConfiguration.xml에 안전 머지 (Horde 등 기존 설정 보존, 엔진 소스/repo 무관).
                    # XML 파싱으로 해당 노드만 갱신/제거 → 다른 설정 안 건드림.
                    ${'$'}mpa = '%MaxParallelActions%'
                    ${'$'}bcFile = Join-Path ${'$'}env:ProgramData 'Unreal Engine\UnrealBuildTool\BuildConfiguration.xml'
                    ${'$'}nsUri = 'https://www.unrealengine.com/BuildConfiguration'
                    if (Test-Path ${'$'}bcFile) {
                        [xml]${'$'}doc = Get-Content -Raw ${'$'}bcFile
                        ${'$'}nsm = New-Object System.Xml.XmlNamespaceManager(${'$'}doc.NameTable)
                        ${'$'}nsm.AddNamespace('u', ${'$'}nsUri)
                        ${'$'}bc = ${'$'}doc.SelectSingleNode('/u:Configuration/u:BuildConfiguration', ${'$'}nsm)
                        ${'$'}node = if (${'$'}bc) { ${'$'}bc.SelectSingleNode('u:MaxParallelActions', ${'$'}nsm) } else { ${'$'}null }
                        if (${'$'}mpa -and ${'$'}mpa.Trim() -and ${'$'}mpa.Trim() -ne '0') {
                            if (-not ${'$'}bc) { ${'$'}bc = ${'$'}doc.CreateElement('BuildConfiguration', ${'$'}nsUri); [void]${'$'}doc.DocumentElement.AppendChild(${'$'}bc) }
                            if (-not ${'$'}node) { ${'$'}node = ${'$'}doc.CreateElement('MaxParallelActions', ${'$'}nsUri); [void]${'$'}bc.AppendChild(${'$'}node) }
                            ${'$'}node.InnerText = ${'$'}mpa.Trim()
                            ${'$'}doc.Save(${'$'}bcFile)
                            Write-Host (">> MaxParallelActions=" + ${'$'}mpa.Trim() + " merged into BuildConfiguration.xml (Horde preserved)")
                        } elseif (${'$'}node) {
                            [void]${'$'}node.ParentNode.RemoveChild(${'$'}node)
                            ${'$'}doc.Save(${'$'}bcFile)
                            Write-Host ">> MaxParallelActions cleared - engine default parallelism"
                        } else {
                            Write-Host ">> MaxParallelActions not set - engine default parallelism"
                        }
                    } else {
                        Write-Host ">> BuildConfiguration.xml not found on agent - skipping MaxParallelActions"
                    }
                    
                    if ('%CleanMode%' -eq 'FullRebuild') {
                        Write-Host ">> CleanMode = FullRebuild → UAT -clean 적용 (아래 args에 추가됨)"
                    }
                    
                    # Sub-step 1a: Generate project files (보통 1-2분, watchdog 불필요)
                    & ".\GenerateProjectFiles.bat"
                    if (${'$'}LASTEXITCODE -ne 0) {
                        Write-Host "##teamcity[buildProblem description='GenerateProjectFiles failed']"
                        exit ${'$'}LASTEXITCODE
                    }
                    
                    # Sub-step 1b: RunUAT BuildGraph — watchdog으로 감싸서 무출력 timeout 적용
                    # TeamCity는 "no output for N min" failure condition을 지원하지 않으므로,
                    # 빌드 머신 성능을 고려해 전체 timeout 대신 무출력 hang만 감지하기 위함.
                    # 정상 빌드는 BuildGraph가 매 초 다수의 컴파일/링크 라인을 emit하므로
                    # 30분 무출력은 거의 확실히 hang 상태로 판단.
                    #
                    # 인자 처리: Start-Process -ArgumentList에 배열을 주면 공백 포함 인자 처리가
                    # cmd.exe로 갈 때 따옴표가 깨짐. -target="Make Installed Build Win64"가
                    # -target=Make / Installed / Build / Win64 4개로 쪼개져서 UAT가 fail함.
                    # 해결: ArgumentList에 따옴표 박힌 단일 문자열로 전달 → cmd가 그대로 파싱.
                    ${'$'}uatLog = [System.IO.Path]::GetTempFileName()
                    ${'$'}uatArgsStr = 'BuildGraph -script="Engine/Build/InstalledEngineBuild.xml" -target="Make Installed Build Win64" -set:WithDDC=false -set:HostPlatformOnly=true -set:GameConfigurations=Development'
                    if ('%CleanMode%' -eq 'FullRebuild') {
                        ${'$'}uatArgsStr += ' -clean'
                    }
                    
                    Write-Host ">> RunUAT BuildGraph 시작 (watchdog: 60분 무활동 시 종료)"
                    Write-Host ">> args: ${'$'}uatArgsStr"
                    ${'$'}uatProc = Start-Process -FilePath ".\Engine\Build\BatchFiles\RunUAT.bat" -ArgumentList ${'$'}uatArgsStr -RedirectStandardOutput ${'$'}uatLog -PassThru -NoNewWindow
                    # Start-Process -PassThru는 핸들을 미리 캐싱 안 하면 종료 후 .ExitCode가 null → 한 번 읽어 캐싱
                    ${'$'}null = ${'$'}uatProc.Handle
                    
                    # Watchdog: '무출력'이 아니라 '무활동(파일 변경 없음)'으로 hang 판정.
                    # UBA 원격 분산/쿠킹/패키징은 stdout이 수십 분 조용해도 정상(빌드 #31 오탐).
                    # stdout 임시파일 + UAT/UBA 로그(Saved/Logs) + UBT 로그의 '최신 수정시각'이
                    # 하나라도 갱신되면 alive. 전부 N분 정지해야 진짜 hang으로 보고 트리 종료.
                    ${'$'}noOutputTimeoutMin = 60
                    ${'$'}activityFiles = @(".\Engine\Programs\UnrealBuildTool\Log.txt", ".\Engine\Programs\UnrealBuildTool\Trace.uba")
                    ${'$'}activityDirs  = @(".\Engine\Programs\AutomationTool\Saved\Logs")
                    ${'$'}lastDisplaySize = 0
                    ${'$'}lastActivity = Get-Date
                    ${'$'}lastNewestTicks = 0
                    ${'$'}lastIoTotal = 0
                    ${'$'}killedByWatchdog = ${'$'}false
                    
                    while (!${'$'}uatProc.HasExited) {
                        Start-Sleep -Seconds 30
                    
                        # --- stdout (Start-Process로 redirect한 임시 파일) ---
                        ${'$'}stdoutSize = if (Test-Path ${'$'}uatLog) { (Get-Item ${'$'}uatLog).Length } else { 0 }
                        if (${'$'}stdoutSize -gt ${'$'}lastDisplaySize) {
                            ${'$'}fs = [System.IO.File]::Open(${'$'}uatLog, 'Open', 'Read', 'ReadWrite')
                            ${'$'}fs.Position = ${'$'}lastDisplaySize
                            ${'$'}sr = New-Object System.IO.StreamReader(${'$'}fs)
                            ${'$'}newContent = ${'$'}sr.ReadToEnd()
                            ${'$'}sr.Close(); ${'$'}fs.Close()
                            if (${'$'}newContent.Trim()) { Write-Host ${'$'}newContent }
                            ${'$'}lastDisplaySize = ${'$'}stdoutSize
                        }
                        # --- 활동 신호: stdout 파일 + 활동 파일/디렉터리 중 가장 최근 수정시각 ---
                        ${'$'}newest = 0
                        foreach (${'$'}p in (@(${'$'}uatLog) + ${'$'}activityFiles)) {
                            if (Test-Path ${'$'}p) { ${'$'}t = (Get-Item ${'$'}p).LastWriteTimeUtc.Ticks; if (${'$'}t -gt ${'$'}newest) { ${'$'}newest = ${'$'}t } }
                        }
                        foreach (${'$'}d in ${'$'}activityDirs) {
                            if (Test-Path ${'$'}d) {
                                ${'$'}f = Get-ChildItem -Path ${'$'}d -File -ErrorAction SilentlyContinue | Sort-Object LastWriteTimeUtc -Descending | Select-Object -First 1
                                if (${'$'}f) { ${'$'}t = ${'$'}f.LastWriteTimeUtc.Ticks; if (${'$'}t -gt ${'$'}newest) { ${'$'}newest = ${'$'}t } }
                            }
                        }
                        if (${'$'}newest -gt ${'$'}lastNewestTicks) { ${'$'}lastNewestTicks = ${'$'}newest; ${'$'}lastActivity = Get-Date }
                    
                        # --- 추가 신호: 빌드 프로세스 트리의 누적 I/O 바이트 ---
                        # 파일 mtime이 못 잡는 단계(예: Make Installed Build의 LocalBuilds 대용량 복사) 커버.
                        # RunUAT 자손 트리의 ReadTransferCount+WriteTransferCount 합이 늘면 alive.
                        ${'$'}ioTotal = 0
                        try {
                            ${'$'}allProc = Get-CimInstance Win32_Process -ErrorAction SilentlyContinue
                            ${'$'}tree = @{}; ${'$'}tree[[int]${'$'}uatProc.Id] = ${'$'}true
                            for (${'$'}pass = 0; ${'$'}pass -lt 8; ${'$'}pass++) {
                                foreach (${'$'}pr in ${'$'}allProc) { if (${'$'}tree[[int]${'$'}pr.ParentProcessId] -and -not ${'$'}tree[[int]${'$'}pr.ProcessId]) { ${'$'}tree[[int]${'$'}pr.ProcessId] = ${'$'}true } }
                            }
                            foreach (${'$'}pr in ${'$'}allProc) { if (${'$'}tree[[int]${'$'}pr.ProcessId]) { ${'$'}ioTotal += [int64]${'$'}pr.ReadTransferCount + [int64]${'$'}pr.WriteTransferCount } }
                        } catch {}
                        if (${'$'}ioTotal -gt ${'$'}lastIoTotal) { ${'$'}lastIoTotal = ${'$'}ioTotal; ${'$'}lastActivity = Get-Date }
                    
                        ${'$'}silentMin = ((Get-Date) - ${'$'}lastActivity).TotalMinutes
                        if (${'$'}silentMin -gt 10) {
                            Write-Host ("[WATCHDOG] no activity {0:N1}m (stdout/logs unchanged, threshold {1}m)" -f ${'$'}silentMin, ${'$'}noOutputTimeoutMin)
                        }
                    
                        # 모든 활동 신호가 N분 정지 → 진짜 hang으로 판정
                        if (${'$'}silentMin -ge ${'$'}noOutputTimeoutMin) {
                            Write-Host ("##teamcity[buildProblem description='WATCHDOG: no build activity for {0} min - hang detected, killing process tree']" -f [int]${'$'}silentMin)
                            # 프로세스 트리 전체 종료 (.Kill()은 부모만 죽여 UBT/UBA 좀비가 뮤텍스 점유 → 다음 빌드 ConflictingInstance)
                            try { taskkill /T /F /PID ${'$'}uatProc.Id 2>${'$'}null | Out-Null } catch { Write-Host "[WATCHDOG] tree kill failed" }
                            # 트리에서 분리됐을 수 있는 UBT/UBA 잔류 정리 (watchdog 발동 시 이 빌드가 유일 → 안전)
                            Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object { ${'$'}_.Name -match 'UbaAgent|UbaServer' -or ${'$'}_.CommandLine -match 'UnrealBuildTool|AutomationTool' } | ForEach-Object { try { Stop-Process -Id ${'$'}_.ProcessId -Force -ErrorAction SilentlyContinue } catch {} }
                            ${'$'}killedByWatchdog = ${'$'}true
                            break
                        }
                    }
                    
                    # 잔여 출력 flush
                    Get-Content ${'$'}uatLog -Raw -ErrorAction SilentlyContinue | ForEach-Object { if (${'$'}_) { Write-Host ${'$'}_ } }
                    Remove-Item ${'$'}uatLog -ErrorAction SilentlyContinue
                    
                    if (${'$'}killedByWatchdog) { exit 124 }  # 124 = GNU timeout convention
                    
                    ${'$'}uatProc.WaitForExit()
                    ${'$'}exitCode = ${'$'}uatProc.ExitCode
                    if (${'$'}null -eq ${'$'}exitCode) { Write-Host ">> WARN: ExitCode가 null - 0으로 간주"; ${'$'}exitCode = 0 }
                    if (${'$'}exitCode -ne 0) {
                        Write-Host "##teamcity[buildProblem description='RunUAT failed with exit code ${'$'}exitCode']"
                        exit ${'$'}exitCode
                    }
                """.trimIndent()
            }
        }
        powerShell {
            name = "Distribute to Shared Folder"
            id = "Distribute_to_Shared_Folder"
            scriptMode = script {
                content = """
                    chcp 65001
                    
                    ${'$'}source = "%teamcity.build.checkoutDir%\LocalBuilds\Engine\Windows"
                    ${'$'}destination = "${'$'}env:UE5_DIST_PATH"
                    
                    if (!(Test-Path ${'$'}destination)) { New-Item -ItemType Directory -Force -Path ${'$'}destination }
                    
                    # robocopy를 background process로 실행하고 60초마다 heartbeat 출력
                    # robocopy는 큰 파일 복사 중 진행률을 \r-only로 emit하므로 (newline 없음),
                    # heartbeat 없이 실행하면 TeamCity가 무출력으로 오인하여 빌드 강제 종료할 수 있음.
                    # /MIR = /E + /PURGE → destination을 source와 정확히 일치 (옛 빌드 잔해 자동 삭제)
                    # /NP   = 진행률 % 출력 제거 (어차피 \r-only라 로그 가독성 저하만 시킴)
                    # /NDL  = directory 목록 출력 제거 (노이즈 감소)
                    ${'$'}tmpLog = [System.IO.Path]::GetTempFileName()
                    ${'$'}rcArgs = @(${'$'}source, ${'$'}destination, '/MIR', '/Z', '/R:5', '/W:5', '/NP', '/NDL')
                    Write-Host ">> robocopy 시작 (mirror): ${'$'}source -> ${'$'}destination"
                    ${'$'}proc = Start-Process -FilePath 'robocopy.exe' -ArgumentList ${'$'}rcArgs -RedirectStandardOutput ${'$'}tmpLog -PassThru -NoNewWindow
                    ${'$'}null = ${'$'}proc.Handle   # 종료 후 .ExitCode가 null 되는 것 방지 (핸들 캐싱)
                    
                    ${'$'}startTime = Get-Date
                    ${'$'}lastSize = 0
                    while (!${'$'}proc.HasExited) {
                        Start-Sleep -Seconds 60
                    
                        # 새로 쓰여진 로그 라인을 stdout으로 흘려보냄 (file 단위 완료 줄 등)
                        if (Test-Path ${'$'}tmpLog) {
                            ${'$'}currentSize = (Get-Item ${'$'}tmpLog).Length
                            if (${'$'}currentSize -gt ${'$'}lastSize) {
                                ${'$'}fs = [System.IO.File]::Open(${'$'}tmpLog, 'Open', 'Read', 'ReadWrite')
                                ${'$'}fs.Position = ${'$'}lastSize
                                ${'$'}sr = New-Object System.IO.StreamReader(${'$'}fs)
                                ${'$'}newContent = ${'$'}sr.ReadToEnd()
                                ${'$'}sr.Close(); ${'$'}fs.Close()
                                if (${'$'}newContent.Trim()) { Write-Host ${'$'}newContent }
                                ${'$'}lastSize = ${'$'}currentSize
                            }
                        }
                    
                        ${'$'}elapsed = ((Get-Date) - ${'$'}startTime).TotalMinutes
                        Write-Host ('[heartbeat] robocopy running for {0:N1} min' -f ${'$'}elapsed)
                    }
                    
                    # 잔여 출력 flush
                    Get-Content ${'$'}tmpLog -Raw -ErrorAction SilentlyContinue | ForEach-Object { if (${'$'}_) { Write-Host ${'$'}_ } }
                    Remove-Item ${'$'}tmpLog -ErrorAction SilentlyContinue
                    
                    ${'$'}proc.WaitForExit()
                    ${'$'}rc = ${'$'}proc.ExitCode
                    if (${'$'}null -eq ${'$'}rc) { Write-Host ">> WARN: robocopy ExitCode가 null - 0으로 간주"; ${'$'}rc = 0 }
                    Write-Host (">> robocopy ExitCode = " + ${'$'}rc + " (0-7=성공, >=8=실패)")
                    if (${'$'}rc -ge 8) { Write-Error "Robocopy failed with code ${'$'}rc" }
                """.trimIndent()
            }
        }
    }
    steps {
        update<PowerShellStep>(0) {
            clearConditions()
            scriptMode = script {
                content = """
                    ${'$'}ErrorActionPreference = 'Stop'
                    
                    # UTF-8 codepage (cmd의 chcp 65001 대응)
                    chcp 65001 | Out-Null
                    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
                    
                    # MaxParallelActions를 머신 BuildConfiguration.xml에 안전 머지 (Horde 등 기존 설정 보존, 엔진 소스/repo 무관).
                    # XML 파싱으로 해당 노드만 갱신/제거 → 다른 설정 안 건드림.
                    ${'$'}mpa = '%MaxParallelActions%'
                    ${'$'}bcFile = Join-Path ${'$'}env:ProgramData 'Unreal Engine\UnrealBuildTool\BuildConfiguration.xml'
                    ${'$'}nsUri = 'https://www.unrealengine.com/BuildConfiguration'
                    if (Test-Path ${'$'}bcFile) {
                        [xml]${'$'}doc = Get-Content -Raw ${'$'}bcFile
                        ${'$'}nsm = New-Object System.Xml.XmlNamespaceManager(${'$'}doc.NameTable)
                        ${'$'}nsm.AddNamespace('u', ${'$'}nsUri)
                        ${'$'}bc = ${'$'}doc.SelectSingleNode('/u:Configuration/u:BuildConfiguration', ${'$'}nsm)
                        ${'$'}node = if (${'$'}bc) { ${'$'}bc.SelectSingleNode('u:MaxParallelActions', ${'$'}nsm) } else { ${'$'}null }
                        ${'$'}linkNode = if (${'$'}bc) { ${'$'}bc.SelectSingleNode('u:MaxLinkActions', ${'$'}nsm) } else { ${'$'}null }
                        if (${'$'}mpa -and ${'$'}mpa.Trim() -and ${'$'}mpa.Trim() -ne '0') {
                            if (-not ${'$'}bc) { ${'$'}bc = ${'$'}doc.CreateElement('BuildConfiguration', ${'$'}nsUri); [void]${'$'}doc.DocumentElement.AppendChild(${'$'}bc) }
                            if (-not ${'$'}node) { ${'$'}node = ${'$'}doc.CreateElement('MaxParallelActions', ${'$'}nsUri); [void]${'$'}bc.AppendChild(${'$'}node) }
                            ${'$'}node.InnerText = ${'$'}mpa.Trim()
                            
                            # OOM 방지를 위해 링크 작업 개수를 1개로 제한
                            if (-not ${'$'}linkNode) { ${'$'}linkNode = ${'$'}doc.CreateElement('MaxLinkActions', ${'$'}nsUri); [void]${'$'}bc.AppendChild(${'$'}linkNode) }
                            ${'$'}linkNode.InnerText = '1'
                            
                            ${'$'}doc.Save(${'$'}bcFile)
                            Write-Host (">> MaxParallelActions=" + ${'$'}mpa.Trim() + ", MaxLinkActions=1 merged into BuildConfiguration.xml (Horde preserved)")
                        } elseif (${'$'}node) {
                            [void]${'$'}node.ParentNode.RemoveChild(${'$'}node)
                            if (${'$'}linkNode) { [void]${'$'}linkNode.ParentNode.RemoveChild(${'$'}linkNode) }
                            ${'$'}doc.Save(${'$'}bcFile)
                            Write-Host ">> MaxParallelActions and MaxLinkActions cleared - engine default parallelism"
                        } else {
                            Write-Host ">> MaxParallelActions not set - engine default parallelism"
                        }
                    } else {
                        Write-Host ">> BuildConfiguration.xml not found on agent - skipping MaxParallelActions"
                    }
                    
                    if ('%CleanMode%' -eq 'FullRebuild') {
                        Write-Host ">> CleanMode = FullRebuild → UAT -clean 적용 (아래 args에 추가됨)"
                    }
                    
                    # Sub-step 1a: Generate project files (보통 1-2분, watchdog 불필요)
                    & ".\GenerateProjectFiles.bat"
                    if (${'$'}LASTEXITCODE -ne 0) {
                        Write-Host "##teamcity[buildProblem description='GenerateProjectFiles failed']"
                        exit ${'$'}LASTEXITCODE
                    }
                    
                    # Sub-step 1b: RunUAT BuildGraph — watchdog으로 감싸서 무출력 timeout 적용
                    # TeamCity는 "no output for N min" failure condition을 지원하지 않으므로,
                    # 빌드 머신 성능을 고려해 전체 timeout 대신 무출력 hang만 감지하기 위함.
                    # 정상 빌드는 BuildGraph가 매 초 다수의 컴파일/링크 라인을 emit하므로
                    # 30분 무출력은 거의 확실히 hang 상태로 판단.
                    #
                    # 인자 처리: Start-Process -ArgumentList에 배열을 주면 공백 포함 인자 처리가
                    # cmd.exe로 갈 때 따옴표가 깨짐. -target="Make Installed Build Win64"가
                    # -target=Make / Installed / Build / Win64 4개로 쪼개져서 UAT가 fail함.
                    # 해결: ArgumentList에 따옴표 박힌 단일 문자열로 전달 → cmd가 그대로 파싱.
                    ${'$'}uatLog = [System.IO.Path]::GetTempFileName()
                    ${'$'}uatArgsStr = 'BuildGraph -script="Engine/Build/InstalledEngineBuild.xml" -target="Make Installed Build Win64" -set:WithDDC=false -set:HostPlatformOnly=true -set:GameConfigurations=Development'
                    if ('%CleanMode%' -eq 'FullRebuild') {
                        ${'$'}uatArgsStr += ' -clean'
                    }
                    
                    Write-Host ">> RunUAT BuildGraph 시작 (watchdog: 60분 무활동 시 종료)"
                    Write-Host ">> args: ${'$'}uatArgsStr"
                    ${'$'}uatProc = Start-Process -FilePath ".\Engine\Build\BatchFiles\RunUAT.bat" -ArgumentList ${'$'}uatArgsStr -RedirectStandardOutput ${'$'}uatLog -PassThru -NoNewWindow
                    # Start-Process -PassThru는 핸들을 미리 캐싱 안 하면 종료 후 .ExitCode가 null → 한 번 읽어 캐싱
                    ${'$'}null = ${'$'}uatProc.Handle
                    
                    # Watchdog: '무출력'이 아니라 '무활동(파일 변경 없음)'으로 hang 판정.
                    # UBA 원격 분산/쿠킹/패키징은 stdout이 수십 분 조용해도 정상(빌드 #31 오탐).
                    # stdout 임시파일 + UAT/UBA 로그(Saved/Logs) + UBT 로그의 '최신 수정시각'이
                    # 하나라도 갱신되면 alive. 전부 N분 정지해야 진짜 hang으로 보고 트리 종료.
                    ${'$'}noOutputTimeoutMin = 60
                    ${'$'}activityFiles = @(".\Engine\Programs\UnrealBuildTool\Log.txt", ".\Engine\Programs\UnrealBuildTool\Trace.uba")
                    ${'$'}activityDirs  = @(".\Engine\Programs\AutomationTool\Saved\Logs")
                    ${'$'}lastDisplaySize = 0
                    ${'$'}lastActivity = Get-Date
                    ${'$'}lastNewestTicks = 0
                    ${'$'}lastIoTotal = 0
                    ${'$'}killedByWatchdog = ${'$'}false
                    
                    while (!${'$'}uatProc.HasExited) {
                        Start-Sleep -Seconds 30
                    
                        # --- stdout (Start-Process로 redirect한 임시 파일) ---
                        ${'$'}stdoutSize = if (Test-Path ${'$'}uatLog) { (Get-Item ${'$'}uatLog).Length } else { 0 }
                        if (${'$'}stdoutSize -gt ${'$'}lastDisplaySize) {
                            ${'$'}fs = [System.IO.File]::Open(${'$'}uatLog, 'Open', 'Read', 'ReadWrite')
                            ${'$'}fs.Position = ${'$'}lastDisplaySize
                            ${'$'}sr = New-Object System.IO.StreamReader(${'$'}fs)
                            ${'$'}newContent = ${'$'}sr.ReadToEnd()
                            ${'$'}sr.Close(); ${'$'}fs.Close()
                            if (${'$'}newContent.Trim()) { Write-Host ${'$'}newContent }
                            ${'$'}lastDisplaySize = ${'$'}stdoutSize
                        }
                        # --- 활동 신호: stdout 파일 + 활동 파일/디렉터리 중 가장 최근 수정시각 ---
                        ${'$'}newest = 0
                        foreach (${'$'}p in (@(${'$'}uatLog) + ${'$'}activityFiles)) {
                            if (Test-Path ${'$'}p) { ${'$'}t = (Get-Item ${'$'}p).LastWriteTimeUtc.Ticks; if (${'$'}t -gt ${'$'}newest) { ${'$'}newest = ${'$'}t } }
                        }
                        foreach (${'$'}d in ${'$'}activityDirs) {
                            if (Test-Path ${'$'}d) {
                                ${'$'}f = Get-ChildItem -Path ${'$'}d -File -ErrorAction SilentlyContinue | Sort-Object LastWriteTimeUtc -Descending | Select-Object -First 1
                                if (${'$'}f) { ${'$'}t = ${'$'}f.LastWriteTimeUtc.Ticks; if (${'$'}t -gt ${'$'}newest) { ${'$'}newest = ${'$'}t } }
                            }
                        }
                        if (${'$'}newest -gt ${'$'}lastNewestTicks) { ${'$'}lastNewestTicks = ${'$'}newest; ${'$'}lastActivity = Get-Date }
                    
                        # --- 추가 신호: 빌드 프로세스 트리의 누적 I/O 바이트 ---
                        # 파일 mtime이 못 잡는 단계(예: Make Installed Build의 LocalBuilds 대용량 복사) 커버.
                        # RunUAT 자손 트리의 ReadTransferCount+WriteTransferCount 합이 늘면 alive.
                        ${'$'}ioTotal = 0
                        try {
                            ${'$'}allProc = Get-CimInstance Win32_Process -ErrorAction SilentlyContinue
                            ${'$'}tree = @{}; ${'$'}tree[[int]${'$'}uatProc.Id] = ${'$'}true
                            for (${'$'}pass = 0; ${'$'}pass -lt 8; ${'$'}pass++) {
                                foreach (${'$'}pr in ${'$'}allProc) { if (${'$'}tree[[int]${'$'}pr.ParentProcessId] -and -not ${'$'}tree[[int]${'$'}pr.ProcessId]) { ${'$'}tree[[int]${'$'}pr.ProcessId] = ${'$'}true } }
                            }
                            foreach (${'$'}pr in ${'$'}allProc) { if (${'$'}tree[[int]${'$'}pr.ProcessId]) { ${'$'}ioTotal += [int64]${'$'}pr.ReadTransferCount + [int64]${'$'}pr.WriteTransferCount } }
                        } catch {}
                        if (${'$'}ioTotal -gt ${'$'}lastIoTotal) { ${'$'}lastIoTotal = ${'$'}ioTotal; ${'$'}lastActivity = Get-Date }
                    
                        ${'$'}silentMin = ((Get-Date) - ${'$'}lastActivity).TotalMinutes
                        if (${'$'}silentMin -gt 10) {
                            Write-Host ("[WATCHDOG] no activity {0:N1}m (stdout/logs unchanged, threshold {1}m)" -f ${'$'}silentMin, ${'$'}noOutputTimeoutMin)
                        }
                    
                        # 모든 활동 신호가 N분 정지 → 진짜 hang으로 판정
                        if (${'$'}silentMin -ge ${'$'}noOutputTimeoutMin) {
                            Write-Host ("##teamcity[buildProblem description='WATCHDOG: no build activity for {0} min - hang detected, killing process tree']" -f [int]${'$'}silentMin)
                            # 프로세스 트리 전체 종료 (.Kill()은 부모만 죽여 UBT/UBA 좀비가 뮤텍스 점유 → 다음 빌드 ConflictingInstance)
                            try { taskkill /T /F /PID ${'$'}uatProc.Id 2>${'$'}null | Out-Null } catch { Write-Host "[WATCHDOG] tree kill failed" }
                            # 트리에서 분리됐을 수 있는 UBT/UBA 잔류 정리 (watchdog 발동 시 이 빌드가 유일 → 안전)
                            Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object { ${'$'}_.Name -match 'UbaAgent|UbaServer' -or ${'$'}_.CommandLine -match 'UnrealBuildTool|AutomationTool' } | ForEach-Object { try { Stop-Process -Id ${'$'}_.ProcessId -Force -ErrorAction SilentlyContinue } catch {} }
                            ${'$'}killedByWatchdog = ${'$'}true
                            break
                        }
                    }
                    
                    # 잔여 출력 flush
                    Get-Content ${'$'}uatLog -Raw -ErrorAction SilentlyContinue | ForEach-Object { if (${'$'}_) { Write-Host ${'$'}_ } }
                    Remove-Item ${'$'}uatLog -ErrorAction SilentlyContinue
                    
                    if (${'$'}killedByWatchdog) { exit 124 }  # 124 = GNU timeout convention
                    
                    ${'$'}uatProc.WaitForExit()
                    ${'$'}exitCode = ${'$'}uatProc.ExitCode
                    if (${'$'}null -eq ${'$'}exitCode) { Write-Host ">> WARN: ExitCode가 null - 0으로 간주"; ${'$'}exitCode = 0 }
                    if (${'$'}exitCode -ne 0) {
                        Write-Host "##teamcity[buildProblem description='RunUAT failed with exit code ${'$'}exitCode']"
                        exit ${'$'}exitCode
                    }
                """.trimIndent()
            }
        }
    }
}
