package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.Perfmon
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'SyncFork'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("SyncFork")) {
    features {
        val feature1 = find<Perfmon> {
            perfmon {
            }
        }
        feature1.apply {
            param("teamcity.perfmon.feature.enabled", "true")
        }
    }
}
