package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "cleanUp"
                id = "PROJECT_CLEANUP_RULE"
                param("keepRule.1.dataToKeep", "everything")
                param("keepRule.1.type", "days")
                param("keepRule.1.days", "10")
            }
        }
    }
}
